language: nodejs

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y sudo apt-get install libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

script:
  - git config user.email "sergets@ya.ru"
  - git config user.name "self-driving Serge Ts"
  - git config remote.origin.url `git config remote.origin.url | sed "s/github.com/sergets:$GITHUB_KEY@github.com/"`
  - git checkout master
  - git submodule update --remote
  - cd mgtmap-checkout
  - npm install yarn
  - make deploy
  - rm -r ../mgtmap
  - mv deploy ../mgtmap
  - cd ..
  - git add . 
  - git commit -m 'Automatically up submodules & deploy mgtmap' && git push || true
